-- 코드를 입력하세요
SELECT * FROM FIRST_HALF;
SELECT * FROM ICECREAM_INFO;


SELECT INFO.INGREDIENT_TYPE, SUM(HALF.TOTAL_ORDER) TOTAL_ORDER 
FROM ICECREAM_INFO INFO 
JOIN FIRST_HALF HALF ON INFO.FLAVOR = HALF.FLAVOR 
GROUP BY INFO.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;